# Generated by Django 5.2.8 on 2025-12-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251209_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='description',
            field=models.TextField(),
        ),
    ]
